//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motorcycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motorcycle()
        {
            this.RentalMotorcycle = new HashSet<RentalMotorcycle>();
        }
    
        public int MotorcycleID { get; set; }
        public int BrandID { get; set; }
        public string Model { get; set; }
        public int TypeID { get; set; }
        public int Year { get; set; }
        public decimal DailyRate { get; set; }
        public bool IsBooked { get; set; }
    
        public virtual MotorcycleBrand MotorcycleBrand { get; set; }
        public virtual MotorcycleType MotorcycleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalMotorcycle> RentalMotorcycle { get; set; }
    }
}
